In [7]:
import dotenv

dotenv.load_dotenv()
import random

import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as sp
from IPython.display import display

import newaresql

You must either set the enviroment variables
- `NEWARE_BTS_HOST`
- `NEWARE_BTS_PORT`
- `NEWARE_BTS_USERNAME`
- `NEWARE_BTS_PASSWORD`
- `NEWARE_BTS_DATABASE`
- 
globally or in the env file, modify the credentials dictionary

In [8]:
credentials = dict(
    host=None,
    port=None,
    username=None,
    password=None,
    database=None,
)

In [21]:
with newaresql.connect(**credentials) as conn:
    tests = conn.get_tests()
    print(f"Found {len(tests)} tests in the database")
    display(tests.head())

Found 3307 tests in the database

shape: (5, 42)
┌─────────┬─────────┬─────────┬────────┬───┬───────────────┬───────────┬──────────────┬────────────┐
│ test_id ┆ dev_uid ┆ unit_id ┆ chl_id ┆ … ┆ update_time   ┆ step_guid ┆ test_guid    ┆ table_name │
│ ---     ┆ ---     ┆ ---     ┆ ---    ┆   ┆ ---           ┆ ---       ┆ ---          ┆ ---        │
│ i64     ┆ i64     ┆ i64     ┆ i64    ┆   ┆ datetime[μs]  ┆ str       ┆ str          ┆ str        │
╞═════════╪═════════╪═════════╪════════╪═══╪═══════════════╪═══════════╪══════════════╪════════════╡
│ 1       ┆ 240005  ┆ 2       ┆ 3      ┆ … ┆ 2024-08-30    ┆           ┆ E089221C57E8 ┆ 20240829   │
│         ┆         ┆         ┆        ┆   ┆ 15:26:26      ┆           ┆ 11EB9B814C34 ┆            │
│         ┆         ┆         ┆        ┆   ┆               ┆           ┆ 883423…      ┆            │
│ 1       ┆ 240005  ┆ 2       ┆ 4      ┆ … ┆ 2024-08-30    ┆           ┆ E089221C57E8 ┆ 20240829   │
│         ┆         ┆         ┆        ┆   ┆ 15:26:47      ┆           ┆ 11EB9B814C34 ┆            │
│         ┆         ┆         ┆        ┆   ┆               ┆           ┆ 883423…      ┆            │
│ 1       ┆ 240005  ┆ 2       ┆ 5      ┆ … ┆ 2024-08-30    ┆           ┆ E089221C57E8 ┆ 20240829   │
│         ┆         ┆         ┆        ┆   ┆ 15:27:45      ┆           ┆ 11EB9B814C34 ┆            │
│         ┆         ┆         ┆        ┆   ┆               ┆           ┆ 883423…      ┆            │
│ 1       ┆ 240005  ┆ 2       ┆ 6      ┆ … ┆ 2024-08-30    ┆           ┆ E089221C57E8 ┆ 20240829   │
│         ┆         ┆         ┆        ┆   ┆ 15:28:04      ┆           ┆ 11EB9B814C34 ┆            │
│         ┆         ┆         ┆        ┆   ┆               ┆           ┆ 883423…      ┆            │
│ 1       ┆ 240005  ┆ 2       ┆ 7      ┆ … ┆ 2024-08-30    ┆           ┆ E089221C57E8 ┆ 20240829   │
│         ┆         ┆         ┆        ┆   ┆ 15:28:33      ┆           ┆ 11EB9B814C34 ┆            │
│         ┆         ┆         ┆        ┆   ┆               ┆           ┆ 883423…      ┆            │
└─────────┴─────────┴─────────┴────────┴───┴───────────────┴───────────┴──────────────┴────────────┘

In [ ]:
with newaresql.connect(**credentials) as conn:
    test = random.choice(tests.to_dicts())
    print(f"Test metadata")
    print(
        "\n".join(
            f"\t{k}: {test[k]}"
            for k in [
                "dev_uid",
                "unit_id",
                "chl_id",
                "test_id",
                "batch_no",
                "info",
                "start_time",
                "end_time",
            ]
        )
    )
    stats = conn.get_stats(test)
    print(f"Test statistics")
    print("\n".join(f"\t{k}: {v}" for k, v in stats.items()))    
    data = conn.get_data(test, conditions={"cycle": (None, 10)}, join="database")
    display(data.head())

    fig = sp.make_subplots(rows=3, cols=1)
    for n, col in enumerate(
        ["Current / A", "Voltage / V", "Temperature / degC"], start=1
    ):
        fig.add_trace(
            go.Scatter(
                x=data.select("Unix Time / s").to_series(),
                y=data.select((col,)).to_series(),
                name=col,
            ),
            row=n,
            col=1,
        )
        fig.update_xaxes(title_text="Unix Time / s", row=n, col=1)
        fig.update_yaxes(title_text=col, row=n, col=1)
    fig.update_layout(width=1000, height=1000)
    fig.show()

Test metadata
	dev_uid: 240002
	unit_id: 1
	chl_id: 1
	test_id: 159
	batch_no: 2048486-ACE-78600-NCM78Ah-613
	info: CCyc_PE_13
	start_time: 2025-11-14 19:41:29
	end_time: None
Test statistics
	record_count: 28854555
	cycle_count: 6398

In [12]:
display(data)

shape: (123_927, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Temperatu ┆ Step Type ┆ Time /    ┆ Current / ┆ … ┆ Cycle     ┆ Step Time ┆ Step      ┆ Step Dis │
│ re / degC ┆ / 1       ┆ datetime  ┆ A         ┆   ┆ Count / 1 ┆ / s       ┆ Capacity  ┆ charging │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ / Ah      ┆ Energy / │
│ f64       ┆ str       ┆ datetime[ ┆ f64       ┆   ┆ i64       ┆ f64       ┆ ---       ┆ Wh       │
│           ┆           ┆ μs]       ┆           ┆   ┆           ┆           ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:32:03  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 1.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:32:04  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 2.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:32:05  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 3.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:32:06  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 4.0       ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 10:32:07  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 24.9      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 596.0     ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 20:49:43  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.9      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 597.0     ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 20:49:44  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.9      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 598.0     ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 20:49:45  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 599.0     ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 20:49:46  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 24.8      ┆ Rest      ┆ 2025-04-0 ┆ 0.0       ┆ … ┆ 0         ┆ 600.0     ┆ 0.0       ┆ 0.0      │
│           ┆           ┆ 3         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 20:49:47  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘